--INSERT INTO role VALUES (1, 'ROLE_ADMIN');
--INSERT INTO role VALUES (2, 'ROLE_USER');
--
---- admin user
--
--insert into user (user_id,username, password, enabled)
--values (1,''admin@admin.com, 'admin', true);
--insert into application_user_role (user_id, role_id)
--values (1,1);
--insert into application_user_role (user_id, role_id)
--values (1,2);